-- function GetAllColorSchemes()
--   local rtp = vim.api.nvim_list_runtime_paths()
--   local unique_colorschemes = {}
--
--   for _, path in pairs(rtp) do
--     local colors_dir = path .. '/colors'
--     -- Check if the colors directory exists before proceeding
--     local files = vim.fn.readdir(colors_dir)
--     for _, file in pairs(files) do
--       if file:match '%.vim$' then
--         local scheme = file:gsub('%.vim$', '')
--         unique_colorschemes[scheme] = {} -- Initialize each scheme with an empty config table
--       end
--     end
--   end
--
--   print(scheme)
--   return unique_colorschemes
-- end

return {
  'wllfaria/scheming.nvim',
  config = function()
    --local schemes = GetAllColorSchemes()
    -- Add predefined or specific configurations for known schemes
    --schemes['catppuccin'] = {} -- Example: Add or modify specific schemes if needed
    require('scheming').setup {
      -- your configuration comes here
      -- or leave it empty to use the default settings
      -- refer to the configuration section below
      mappings = {
        toggle = {
          '<leader>cs',
        },
      },
      schemes = {
        'OceanicNext',
        'OceanicNextLight',
        'apprentice',
        'aquarium',
        'ariake',
        'aurora',
        'blue',
        'blue-moon',
        'calvera',
        'carbonfox',
        'catppuccin',
        'catppuccin-frappe',
        'catppuccin-latte',
        'catppuccin-macchiato',
        'catppuccin-mocha',
        'codedark',
        'codeschool',
        'darkblue',
        'darker',
        'darksolar',
        'dawnfox',
        'dayfox',
        'deepocean',
        'default',
        'delek',
        'desert',
        'dracula',
        'dracula_blood',
        'duckbones',
        'duskfox',
        'earlysummer',
        'earlysummer_lighter',
        'edge',
        'elflord',
        'embark',
        'emerald',
        'evening',
        'everforest',
        'falcon',
        'fluoromachine',
        'forestbones',
        'github-colors',
        'github_dark',
        'github_dark_colorblind',
        'github_dark_default',
        'github_dark_dimmed',
        'github_dark_high_contrast',
        'github_dark_tritanopia',
        'github_dimmed',
        'github_light',
        'github_light_colorblind',
        'github_light_default',
        'github_light_high_contrast',
        'github_light_tritanopia',
        'gloombuddy',
        'gruvbox',
        'gruvbox-baby',
        'gruvbox-material',
        'gruvy',
        'habamax',
        'industry',
        'kanagawa',
        'kanagawa-dragon',
        'kanagawa-lotus',
        'kanagawa-wave',
        'kanagawabones',
        'koehler',
        'limestone',
        'lunaperche',
        'lunar',
        'mariana',
        'mariana_lighter',
        'mellow',
        'metanoia',
        'miasma',
        'middlenight_blue',
        'monochrome',
        'monokai',
        'monokai_lighter',
        'monokai_pro',
        'monokai_ristretto',
        'monokai_soda',
        'moonfly',
        'moonlight',
        'morning',
        'murphy',
        'neobones',
        'neon',
        'neosolarized',
        'nightfly',
        'nightfox',
        'nord',
        'nordbones',
        'nordfox',
        'nordic',
        'nvcode',
        'nvim-hybrid',
        'nvimgelion',
        'oceanic',
        'ofirkai',
        'ofirkai-darkblue',
        'omni',
        'one-nvim',
        'onebuddy',
        'onedark',
        'onedark_dark',
        'onedark_vivid',
        'onelight',
        'pablo',
        'palenight',
        'peachpuff',
        'quiet',
        'rasmus',
        'ron',
        'rosebones',
        'seoulbones',
        'sherbet',
        'sherbet-italic',
        'shine',
        'slate',
        'snazzy',
        'sonokai',
        'space-nvim',
        'starry',
        'substrata',
        'terafox',
        'tokyobones',
        'torte',
        'ukraine',
        'vimbones',
        'vimdark',
        'vimlight',
        'visual_studio_code',
        'vn-night',
        'xoria',
        'zellner',
        'zenbones',
        'zenburned',
        'zenwritten',
        'zephyrium',
      },
    }
  end,
}
